export const STORAGE_KEY = "project-26-state-v2";
export const LEGACY_STORAGE_KEYS = ["project-26-state"];

export const ACTIVITY_GROUPS = [
  {
    id: "fitness",
    title: "Fitness",
    items: [
      { id: "push-up", name: "Push-Up", rate: 1, unit: "rep", step: 1 },
      { id: "triangle", name: "Triangle Push-Up", rate: 2, unit: "rep", step: 1 },
      { id: "decline", name: "Decline Push-Up", rate: 2, unit: "rep", step: 1 },
      { id: "dip", name: "Dip", rate: 1, unit: "rep", step: 1 },
      { id: "sit-up", name: "Sit-Up", rate: 1, unit: "rep", step: 1 },
      { id: "chin-up", name: "Chin-Up", rate: 2, unit: "rep", step: 1 },
      { id: "pull-up", name: "Pull Up", rate: 3, unit: "rep", step: 1 },
      { id: "squat", name: "Squat", rate: 1, unit: "rep", step: 1 },
      { id: "lunge", name: "Lunge", rate: 1, unit: "rep", step: 1 },
      { id: "plank-30", name: "30 Sec Plank", rate: 10, unit: "set", step: 1 },
      { id: "plank-60", name: "1 Min Plank", rate: 25, unit: "set", step: 1 },
      { id: "run", name: "Run", rate: 25, unit: "km", step: 0.1 },
      { id: "walk", name: "Walk", rate: 7, unit: "km", step: 0.1 },
      { id: "bike", name: "Bike", rate: 5, unit: "km", step: 0.1 },
      { id: "steps", name: "Step", rate: 0.005, unit: "step", step: 1 },
    ],
  },
  {
    id: "growth",
    title: "Learning and practice",
    items: [
      { id: "practice", name: "Practice", rate: 100, unit: "session", step: 1 },
      { id: "study", name: "Study", rate: 2, unit: "minute", step: 1 },
      { id: "story-read", name: "Read (Story)", rate: 1, unit: "minute", step: 1 },
      { id: "learning-read", name: "Read (Learning)", rate: 2, unit: "minute", step: 1 },
      { id: "print-time", name: "3D Printing", rate: 1, unit: "minute", step: 1 },
      { id: "print-design", name: "3D Printing Design", rate: 10, unit: "design", step: 1 },
      { id: "meditate", name: "Meditate", rate: 3, unit: "minute", step: 1 },
      { id: "scriptures", name: "Read Scriptures", rate: 3, unit: "minute", step: 1 },
    ],
  },
  {
    id: "life",
    title: "Life admin and habits",
    items: [
      { id: "dishes", name: "Dishes", rate: 50, unit: "task", step: 1 },
      { id: "dishwasher", name: "Dishwasher", rate: 20, unit: "task", step: 1 },
      { id: "sweep", name: "Sweep", rate: 20, unit: "task", step: 1 },
      { id: "cupboards", name: "Wipe Down Cupboards", rate: 15, unit: "task", step: 1 },
      { id: "cold-shower", name: "Cold Shower", rate: 20, unit: "task", step: 1 },
      { id: "journal", name: "Journal", rate: 30, unit: "entry", step: 1 },
      { id: "church", name: "Church / YM", rate: 75, unit: "visit", step: 1 },
      { id: "cook", name: "Cook / Bake", rate: 2, unit: "minute", step: 1 },
      { id: "real-dollar", name: "$1 In Real Life", rate: 2, unit: "dollar", step: 1 },
    ],
  },
];

export const REWARD_ITEMS = [
  { id: "screen-time", name: "Screen Time", cost: 3, unit: "minute" },
  { id: "soda-stream", name: "Soda Stream", cost: 100, unit: "reward" },
  { id: "movie", name: "Movie", cost: 100, unit: "reward" },
  { id: "pop", name: "Pop", cost: 500, unit: "reward" },
];

export const RESOURCE_ITEMS = [
  { id: "wood-boards", name: "Wood Boards", unit: "board", price: 2 },
  { id: "trees", name: "Trees", unit: "tree", price: null, priceNote: "Not sellable" },
  { id: "sand", name: "Sand", unit: "ton", price: 5 },
  { id: "gravel", name: "Gravel", unit: "ton", price: 10 },
  { id: "limestone", name: "Limestone", unit: "ton", price: 10 },
  { id: "concrete", name: "Concrete", unit: "ton", price: 30 },
  { id: "iron", name: "Iron", unit: "ton", price: 15 },
  { id: "dirt", name: "Dirt", unit: "ton", price: 3 },
  { id: "salt", name: "Salt", unit: "ton", price: 10 },
  { id: "metal", name: "Metal", unit: "ton", price: 25 },
  { id: "glass", name: "Glass", unit: "ton", price: 40 },
  { id: "soda-ash", name: "Soda Ash", unit: "ton", price: 20 },
  { id: "paper", name: "Paper", unit: "sheet", price: 0.004, priceNote: "Calculated from $20 per 5000 paper" },
  { id: "carrot", name: "Carrot", unit: "lb", price: 10 },
  { id: "cotton", name: "Cotton", unit: "lb", price: 1 },
  { id: "potato", name: "Potato", unit: "lb", price: 2 },
  { id: "eggs", name: "Eggs", unit: "egg", price: 0.75 },
  { id: "chicken", name: "Chicken", unit: "animal", price: null, saleMode: "asset", assetId: "chicken", priceNote: "Not sellable" },
  { id: "sheep", name: "Sheep", unit: "animal", price: null, saleMode: "asset", assetId: "sheep", priceNote: "Not sellable" },
  { id: "pig", name: "Pig", unit: "animal", price: null, saleMode: "asset", assetId: "pig", priceNote: "Not sellable" },
  { id: "solar-panels", name: "Solar Panels", unit: "panel", price: 50 },
  { id: "energy", name: "Energy", unit: "energy", price: 5 },
];

export const ASSET_GROUPS = [
  {
    id: "resources",
    title: "Resource extraction",
    items: [
      {
        id: "sand-pit",
        name: "Sand Pit",
        category: "Resource",
        unique: true,
        buildCosts: { "wood-boards": 100, concrete: 8 },
        details: ["Build materials: 100 Boards, 8 Concrete", "Produces sand and gravel automatically each month."],
        levels: [
          { level: 1, cost: 500, outputs: { sand: 10, gravel: 2 } },
        ],
      },
      {
        id: "iron-mine",
        name: "Iron Mine",
        category: "Resource",
        unique: true,
        buildCosts: { "wood-boards": 100, concrete: 10, iron: 10 },
        details: ["Build materials: 100 Boards, 10 Concrete, 10 Iron", "Produces iron automatically each month."],
        levels: [
          { level: 1, cost: 750, outputs: { iron: 10 } },
        ],
      },
      {
        id: "salt-mine",
        name: "Salt Mine",
        category: "Resource",
        unique: true,
        buildCosts: { "wood-boards": 75, concrete: 6, iron: 5 },
        details: ["Build materials: 75 Boards, 6 Concrete, 5 Iron", "Produces salt automatically each month."],
        levels: [
          { level: 1, cost: 600, outputs: { salt: 10 } },
        ],
      },
      {
        id: "limestone-site",
        name: "Limestone Site",
        category: "Resource",
        unique: true,
        buildCosts: { "wood-boards": 100, concrete: 8, iron: 5 },
        details: ["Build materials: 100 Boards, 8 Concrete, 5 Iron", "Produces limestone automatically each month."],
        levels: [
          { level: 1, cost: 500, outputs: { limestone: 10 } },
        ],
      },
      {
        id: "gravel-pit",
        name: "Gravel Pit",
        category: "Resource",
        unique: true,
        buildCosts: { "wood-boards": 100, concrete: 8, iron: 5 },
        details: ["Build materials: 100 Boards, 8 Concrete, 5 Iron", "Produces gravel automatically each month."],
        levels: [
          { level: 1, cost: 600, outputs: { gravel: 10 } },
        ],
      },
      {
        id: "dirt-pit",
        name: "Dirt Pit",
        category: "Resource",
        unique: true,
        buildCosts: { "wood-boards": 75, concrete: 6, iron: 3 },
        details: ["Build materials: 75 Boards, 6 Concrete, 3 Iron", "Produces dirt automatically each month."],
        levels: [
          { level: 1, cost: 200, outputs: { dirt: 10 } },
        ],
      },
    ],
  },
  {
    id: "industry",
    title: "Factories and processing",
    items: [
      {
        id: "concrete-mixer",
        name: "Concrete Mixer",
        category: "Factory",
        unique: true,
        buildCosts: {},
        details: ["Uses sand, gravel, and limestone to make concrete every month."],
        levels: [
          { level: 1, cost: 1000, inputs: { sand: 5, gravel: 10, limestone: 5 }, outputs: { concrete: 5 } },
        ],
      },
      {
        id: "lumber-mill",
        name: "Lumber Mill",
        category: "Factory",
        unique: true,
        buildCosts: { "wood-boards": 50 },
        details: ["Build materials: 50 Boards", "Turns trees into boards. Plywood from the sheet is not tracked yet."],
        levels: [
          { level: 1, cost: 500, inputs: { trees: 50 }, outputs: { "wood-boards": 250 } },
        ],
      },
      {
        id: "paper-factory",
        name: "Paper Factory",
        category: "Factory",
        unique: true,
        buildCosts: { "wood-boards": 75 },
        details: ["Build materials: 75 Boards", "Turns trees into paper. Cardstock is not tracked separately yet."],
        levels: [
          { level: 1, cost: 1000, inputs: { trees: 30 }, outputs: { paper: 150000 } },
        ],
      },
      {
        id: "soda-ash-factory",
        name: "Soda Ash Factory",
        category: "Factory",
        unique: true,
        buildCosts: { "wood-boards": 100 },
        details: ["Build materials: 100 Boards", "Turns salt and limestone into soda ash each month."],
        levels: [
          { level: 1, cost: 1000, inputs: { salt: 10, limestone: 8 }, outputs: { "soda-ash": 10 } },
        ],
      },
      {
        id: "glass-factory",
        name: "Glass Factory",
        category: "Factory",
        unique: true,
        buildCosts: { "wood-boards": 150 },
        details: ["Build materials: 150 Boards", "Turns sand, limestone, and soda ash into glass each month."],
        levels: [
          { level: 1, cost: 1500, inputs: { sand: 10, limestone: 2, "soda-ash": 2 }, outputs: { glass: 10 } },
        ],
      },
      {
        id: "metal-foundry",
        name: "Metal Foundry",
        category: "Factory",
        unique: true,
        buildCosts: { "wood-boards": 100, concrete: 8, iron: 10 },
        details: ["Build materials: 100 Boards, 8 Concrete, 10 Iron", "Turns iron into metal each month."],
        levels: [
          { level: 1, cost: 750, inputs: { iron: 10 }, outputs: { metal: 10 } },
        ],
      },
      {
        id: "solar-factory",
        name: "Solar Factory",
        category: "Factory",
        unique: true,
        buildCosts: { "wood-boards": 150 },
        details: ["Build materials: 150 Boards", "Uses glass and metal to make panels. Silicone from the sheet is assumed for now."],
        levels: [
          { level: 1, cost: 2000, inputs: { glass: 7.5, metal: 7.5 }, outputs: { "solar-panels": 30 } },
        ],
      },
    ],
  },
  {
    id: "land",
    title: "Land, crops, animals, and power",
    items: [
      {
        id: "tree-farm",
        name: "Tree Farm",
        category: "Land",
        repeatable: true,
        details: ["Generates 40 trees each month."],
        levels: [{ level: 1, cost: 3200, outputs: { trees: 40 } }],
      },
      {
        id: "cotton-acre",
        name: "Cotton Acre",
        category: "Crop",
        repeatable: true,
        details: ["Each acre produces 50 lbs of cotton every month."],
        levels: [{ level: 1, cost: 150, outputs: { cotton: 50 } }],
      },
      {
        id: "potato-acre",
        name: "Potato Acre",
        category: "Crop",
        repeatable: true,
        details: ["Each acre produces 50 lbs of potatoes every month."],
        levels: [{ level: 1, cost: 325, outputs: { potato: 50 } }],
      },
      {
        id: "carrot-acre",
        name: "Carrot Acre",
        category: "Crop",
        repeatable: true,
        details: ["Each acre produces 50 lbs of carrots every month."],
        levels: [{ level: 1, cost: 1200, outputs: { carrot: 50 } }],
      },
      {
        id: "hydro-site",
        name: "Hydro Site",
        category: "Energy",
        repeatable: true,
        details: ["Each site produces 35 energy per month."],
        levels: [{ level: 1, cost: 2500, outputs: { energy: 35 } }],
      },
      {
        id: "coal-plant",
        name: "Coal Power Plant",
        category: "Energy",
        repeatable: true,
        details: ["Each plant produces 35 energy per month."],
        levels: [{ level: 1, cost: 3500, outputs: { energy: 35 } }],
      },
      {
        id: "chicken-acre",
        name: "Chicken Acre",
        category: "Animal Land",
        repeatable: true,
        capacityProvided: 500,
        details: ["Each acre costs $125 and supports up to 500 chickens."],
        levels: [{ level: 1, cost: 125 }],
      },
      {
        id: "chicken",
        name: "Chicken",
        category: "Livestock",
        repeatable: true,
        requiresCapacityFrom: "chicken-acre",
        capacityLabel: "Chicken Acre",
        details: ["Requires chicken acreage. Each chicken lays 30 eggs per month."],
        levels: [{ level: 1, cost: 5, outputs: { eggs: 30 } }],
      },
      {
        id: "pig-acre",
        name: "Pig Acre",
        category: "Animal Land",
        repeatable: true,
        capacityProvided: 50,
        details: ["Each acre costs $125 and supports up to 50 pigs."],
        levels: [{ level: 1, cost: 125 }],
      },
      {
        id: "pig",
        name: "Pig",
        category: "Livestock",
        repeatable: true,
        requiresCapacityFrom: "pig-acre",
        capacityLabel: "Pig Acre",
        details: ["Requires pig acreage before purchase."],
        levels: [{ level: 1, cost: 25 }],
      },
      {
        id: "sheep-acre",
        name: "Sheep Acre",
        category: "Animal Land",
        repeatable: true,
        capacityProvided: 50,
        details: ["Each acre costs $125 and supports up to 50 sheep."],
        levels: [{ level: 1, cost: 125 }],
      },
      {
        id: "sheep",
        name: "Sheep",
        category: "Livestock",
        repeatable: true,
        requiresCapacityFrom: "sheep-acre",
        capacityLabel: "Sheep Acre",
        details: ["Requires sheep acreage before purchase."],
        levels: [{ level: 1, cost: 50 }],
      },
    ],
  },
];
